name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  fileName:  # id of input
    description: 'added as prefix of package name.'
    required: true
    default: 'source'
  gitSha:  # id of input
    description: 'The commit SHA of recently commit.'
    required: false
outputs:
  packageName: # id of output
    description: 'the name of release package'
runs:
  using: 'node12'
  main: 'dist/index.js'